# Generated by Django 4.0.3 on 2022-04-12 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CollageApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CollageApp.tutor'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CollageApp.course'),
        ),
    ]
