# Generated by Django 4.0.3 on 2022-04-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollageApp', '0002_student_tutor_tutor_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_fee',
            field=models.IntegerField(null=True),
        ),
    ]
