# Generated by Django 4.0.3 on 2022-04-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollageApp', '0004_rename_student_dob_student_student_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='student_first_name',
        ),
        migrations.AddField(
            model_name='student',
            name='student_last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
